name: eazy_router
description: "A flexible and easy-to-use navigation package for Flutter that leverages code generation to simplify route management"
version: 1.0.0-dev.3
homepage: https://github.com/melWiss/eazy_router

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
