name: eazy_router
description: "A flexible and easy-to-use navigation package for Flutter that leverages code generation to simplify route management"
version: 0.0.3
homepage: https://github.com/melWiss/eazy_router

environment:
  sdk: ^3.3.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
