targets:
  $default:
    builders:
      eazy_router_generator|eazy_router_generator:
        generate_for:
          - lib/**.dart
      eazy_router_generator|eazy_router_registrar:
        generate_for:
          - lib/**.g.dart


builders:
  eazy_router_generator:
    import: "package:eazy_router_generator/eazy_router_generator.dart"
    builder_factories: ["generateRoute"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".route.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
    runs_before: ["eazy_router_generator|eazy_router_registrar"]
  eazy_router_configure_registrar:
    import: "package:eazy_router_generator/eazy_router_generator.dart"
    builder_factories: ["configureRouteRegistrar"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".registrar.json"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
    runs_before: ["eazy_router_generator|eazy_router_registrar"]
  eazy_router_registrar:
    import: "package:eazy_router_generator/eazy_router_generator.dart"
    builder_factories: ["registerRoute"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".registrar.g.part"] }
    auto_apply: dependents
    build_to: source
    required_inputs: ["**/*.registrar.json"]  # Include the pre-built files as required inputs
