name: eazy_router_generator
description: "The code generator of eazy_router package."
version: 1.0.0-dev.1
homepage: https://github.com/melWiss/eazy_router

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: 2.4.1
  source_gen: 1.5.0
  analyzer:
  eazy_router: 1.0.0-dev.1
  glob: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner:
