name: eazy_router_generator
description: "The code generator of eazy_router package."
version: 0.0.3
homepage: https://github.com/melWiss/eazy_router

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build:
  source_gen:
  analyzer:
  eazy_router_annotation: ^0.0.1
  glob: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner:
