name: eazy_router_generator
description: "The code generator of eazy_router package."
version: 1.0.0-dev.5
homepage: https://github.com/melWiss/eazy_router

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  build: ^2.1.0
  source_gen: ^2.0.0
  analyzer:
  eazy_router: 1.0.0-dev.5
  glob: ^2.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner:
